name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download a file
        uses: carlosperate/download-file-action@v2
        with:
          file-url: 'https://github.com/videlais/extwee/raw/develop/build/extwee.exe'
          
      - name: build game
        run: |
          extwee -h

