name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
      - uses: actions/checkout@v4

      - name: Download Tweego
        uses: schmiddim/action-wget-unzip@v2
        with:
          url: 'https://github.com/tmedwards/tweego/releases/download/v2.1.1/tweego-2.1.1-linux-x64.zip'
          destination: .

      - name: test run
        run: ls
