name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Clone tmedwards/tweego
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3 
        with:
          owner: 'tmedwards'
          repository: 'tweego'
          branch: 'master'
          
      - name: Build game
        run: |
          ls -l

