name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.13.1'

      - name: Install Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: vx.x.x
          
      - name: Clone sizhongbin/tweego
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3 
        with:
          owner: 'sizhongbin'
          repository: 'tweego'
          branch: 'master'
          
      - name: Build game
        run: |
          cd tweego
          go get
          go install
          cd ..
          mkdir -p dist && touch dist/index.html
          tweego story -o dist/index.html

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "soragame"
          root: "dist"
          entrypoint: "https://deno.land/std@0.221.0/http/file_server.ts"
