name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.13.1'
          
      - name: Clone Tweego
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3 
        with:
          owner: 'sizhongbin'
          repository: 'tweego'
          branch: 'master'

      - name: Clone SugarCube v2
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3 
        with:
          owner: 'sizhongbin'
          repository: 'sugarcube-2'
          branch: 'v2-develop'
          
      - name: Build index.html
        run: |
          mkdir storyformats
          cp -r sugarcube-2/dist storyformats/sugarcube-2
          cd tweego
          go get
          go install
          cd ..
          mkdir -p dist && touch dist/index.html
          tweego story -o dist/index.html
          echo "sora.zsi.us.kg" > dist/CNAME

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
