name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.13.1'

      - name: Clone tmedwards/tweego
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3 
        with:
          owner: 'tmedwards'
          repository: 'tweego'
          branch: 'master'
          
      - name: Build game
        run: |
          cd tweego
          go get
          go install
          ls

