name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Download Tweego
        uses: robinraju/release-downloader@v1.9
        with:
          repository: "tmedwards/tweego"
          latest: true
          fileName: "*-linux-x64.zip"
          extract: true

      - name: test run
        run: |
          chmod 777 tweego
          ls -l
          ./tweego -v
