name: Build

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 1.18.2

      - name: Install Ctl
        run: deno install -Arf https://deno.land/x/deploy/deployctl.ts

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: sora
          entrypoint: index.html
